#!/bin/bash

#
# clean
rm -rf ./tmp/ ./generated/
mkdir -p ./generated/.vim/colors
mkdir -p ./generated/themer
mkdir -p $HOME/.zsh

#
# configure
if [ -z ${OS+x} ]; then
    echo -e "Env OS not set, assuming osx"
    OS="osx"
fi

FORCE=0
# THEME="./misc/themes/themer-default.colors"
THEME="./misc/themes/monogreen-v5.colors"
VRC_DEST=$HOME/.vimrc
VIMFILES=./generated/.vim
V=./vim
VRC=./generated/.vimrc
CP=cp
:>$VRC

while test $# -gt 0; do
  case "$1" in
    -f|--f|--force)
	  FORCE=1
	  break
      ;;
    *)
      break
      ;;
  esac	
done

# prereqs
yarn install

#
# OS Specific

# brew's recursive copy is broke
if [ "$OS" = "osx" ]; then
  VRC_DEST=$HOME/_vimrc
  CP="/bin/cp"

  echo "\" osx-specific vim comfig via plato/dotfiles" >> ./generated/vimfiles/platform.vimrc
  cat $V/osx.vimrc >> $VIMFILES/platform.vimrc
fi

if [ "$OS" = "windows" ]; then
  VIMFILES=$HOME/_vim
  VRC_DEST=$HOME/_vimrc
fi

if [ "$OS" = "linux" ]; then
  ./node_modules/.bin/themer -t themer-xresources -c $THEME -o ./tmp
  $CP tmp/themer-xresources/themer-xresources-dark/.Xresources ./generated
fi


#
# theming
echo "generating themes..."
./node_modules/.bin/themer -t themer-hyper -t themer-wallpaper-block-wave -t themer-vim -c $THEME -o tmp/
# ./node_modules/.bin/themer -t themer-xterm -t themer-hyper -t themer-wallpaper-block-wave -t themer-vim -t themer-xresources -c $THEME -o tmp/
$CP tmp/themer-vim/ThemerVim.vim ./generated/.vim/colors
# $CP tmp/themer-hyper...

set -e
#
# concat X config and generated xresources theme
while read line
do
  echo $line >> ./generated/.Xresources
done < ./dotfiles/.Xresources
while read line
do
  echo $line >> ./generated/.Xresources
done < ./tmp/themer-xresources/themer-xresources-dark/.Xresources


#
# vim
function appendVimComment() {
  printf "\"\n\" $1\n" >> $VRC
}

appendVimComment "Generated by github.com/therealplato/plato-dotfiles/vim/build.sh"

appendVimComment "sensible.vim"
cat $V/sensible.vim >> $VRC

appendVimComment "plugins.vimrc"
cat $V/plugins.vimrc >> $VRC

appendVimComment "config.vimrc"
cat $V/config.vimrc >> $VRC

appendVimComment "ui.vimrc"
cat $V/ui.vimrc >> $VRC

appendVimComment "binds.vimrc"
cat $V/binds.vimrc >> $VRC

appendVimComment "go.vimrc"
cat $V/go.vimrc >> $VRC

echo "generated $(wc -l $VRC | grep -Eo ^[0-9]+) lines of vimrc"

if [ $FORCE -eq 1 ]; then
  $CP -R ./generated/ $HOME
  # $CP -v $VRC $VRC_DEST
  # $CP -vr ./generated/.vim/colors $VIMFILES
  # $CP -v ./generated/.Xresources $HOME
  $CP -v dotfiles/.screenrc $HOME
  $CP -v dotfiles/.zshrc $HOME
  $CP -rv zsh/* $HOME/.zsh
fi
